### ISSUE TITLE
Use create-session REST API that returns JSON data

### ISSUE THREAD

**Issue by rhainer** [opentok/Opentok-Java-SDK#106]
There is a new version of the create-session REST API that returns JSON data when you include an "Accept: application/json" header in the request. If this is used the XML library dependency can be eliminated.

**Comment by SMadani** [comment]
A complete rewrite of the SDK is in the works, will be integrated in [Vonage/vonage-java-sdk](https://github.com/Vonage/vonage-java-sdk). Can't provide any timelines for GA but there's currently a branch with beta versions.
