### ISSUE TITLE
Can you port a version for Android

### ISSUE THREAD

**Issue by HuuNguyen312** [opentok/Opentok-Java-SDK#120]
Hi

I can't use your library for Android. Can you  port a version for Android

Thanks

**Comment by ngochuu90** [comment]
.

**Comment by msach22** [comment]
@HuuNguyen312 At this time, we don't have any plans to port a version for Android, but we'll be happy to take any PRs if anyone wants to contribute.

**Comment by devwithzachary** [comment]
To confirm there is an Android SDK which you can find at [https://tokbox.com/developer/sdks/android/](https://tokbox.com/developer/sdks/android/) this isn't a "port" of the Java SDK but its own SDK that provides client-side functionality.
