### ISSUE TITLE
close never invoked on internal AsyncHttpClient

### ISSUE THREAD

**Issue by davideberlein** [opentok/Opentok-Java-SDK#121]
The internal ning AsyncHttpClient you are using must be closed after usage which is never done in the OpenTok class.
Also you don't provide a close method to your OpenTok class which would work as an alternative.

If this is not done the HttpClient will leak open file handles. (for us it was 15 per construction of the OpenTok class which is quite a number...)

This has led to hitting max open file handles on our Servers running OpenTok and took quite some time to track down for us.

Since you made the client flied protected on the OpenTok class we could extend it and call the close ourselves as a workaround however the close method should at least be added to your API as well as to your examples because otherwise you are going to produce quite a number of leaked open file handles.

**Comment by chrisgradl** [comment]
Yes please fix this i run into the same issue 
@davideberlein thank you for the tip

**Comment by aiham** [comment]
@davideberlein Will this do for now?

I think it'll be a more substantial change to automatically close the HttpClient since at the moment we only ever instantiate it once and keep a hold of it for the full life of the OpenTok instance.

**Comment by davideberlein** [comment]
@aiham yes I guess that should be enough for now. That's what we are doing via a subclass at the moment.
