### ISSUE TITLE
OpenTok.listArchives() does not support filtering by session ID

### ISSUE THREAD

**Issue by jeffswartz** [opentok/Opentok-Java-SDK#122]
The OpenTok REST API now lets you filter by session ID when getting a list of archives: https://tokbox.com/developer/rest/#listing_archives. (You pass in a `sessionId` query parameter when calling the REST API method.) The `OpenTok.listArchives()` methods in the OpenTok Java server SDK does not support this session ID filter.

**Comment by davideberlein** [comment]
We need exactly the same feature!

**Comment by rschlick** [comment]
+1

**Comment by aiham** [comment]
Fixed in #132
