### ISSUE TITLE
Support for video layout for composed archives

### ISSUE THREAD

**Issue by carlov20** [opentok/Opentok-Java-SDK#131]
Is there any time scale for when this SDK will support this https://tokbox.com/developer/guides/archiving/layout-control.html ?

**Comment by puneetshettyp** [comment]
Hi Carlo 

We have also received the support ticket for this request. Please note that there is no planned update to the Server SDKs this quarter. As per our current roadmap, we will aim to add the missing REST end-points to all our Server SDKs in Q4, i.e Oct-Dec time-frame. Hope this helps

Regards
Puneet, TokBox

**Comment by tonycapone** [comment]
With the above changes merged in to dev, do you have plans to cut a new release for this project? Thanks.

**Comment by aiham** [comment]
@tonycapone Done! Thanks for your patience.
