### ISSUE TITLE
generated tokens are invalid

### ISSUE THREAD

**Issue by EmreAkkoyun** [opentok/Opentok-Java-SDK#135]
Hi guys;

Im using opentok java server sdk 4.0.0 version.  I create sessionId and token from that sdk and pass that values to client side and it gives "Connect Error: Invalid token format (1004)". And i couldnt pass that error.

But when i create session Id and token from tokbox UI and pass that values to client side statically it works fine. How can i pass that error?

Thanks

**Comment by aullman** [comment]
@EmreAkkoyun could you share an example of the Token and sessionId that is invalid so we can try to determine what could be wrong with it? It can be an expired one so nobody can use it.

**Comment by EmreAkkoyun** [comment]
Hi Adam;

Thanks for you response.
When i deployed my backend application (Spring Boot - Java app) it works
well. But at my local environment it gives me 1004 unauthorized token error.

I will share sessionId and the tokenId with you

Thanks
Emre

**Comment by aullman** [comment]
Ah, my guess is that the clock on your local environment is not set correctly and the tokens that are being generated are already expired. Is that possible?

**Comment by aiham** [comment]
@EmreAkkoyun Did your resolve this issue? I'm closing this for now. Feel free to request to reopen this issue if you can provide more information. Thanks
