### ISSUE TITLE
Add dial() API

### ISSUE THREAD

**Issue by oripwk** [opentok/Opentok-Java-SDK#141]
OpenTok's REST API, as well as some other clients (such as JS), have the `dial(…)` [functionality](https://tokbox.com/developer/rest/#sip_call).

Is it possible to add the functionality to the Java SDK as well?

**Comment by aladante** [comment]
I would very much like to have this functionality as well, so I don't have to create another client application 👍

**Comment by msach22** [comment]
@oripwk @aladante We are working on some plans to support the other REST endpoints. I will update the issue as I have some more information!

**Comment by msach22** [comment]
@aladante I'll be submitting a public API proposal for the `dial` API. Will keep you all updated!

**Comment by aladante** [comment]
Thanks @msach22

**Comment by aladante** [comment]
Are there any updates yet?

**Comment by msach22** [comment]
@aladante Sorry for the delay, this API is a WIP and we're hoping to have it complete in the next week or so. You can check the [dev branch](https://github.com/opentok/Opentok-Java-SDK/tree/dev) for the latest updates.

**Comment by msach22** [comment]
Hey folks, the merge is in the dev branch - please feel free to use that as needed.

**Comment by msach22** [comment]
This has been released with `4.3.0`
