### ISSUE TITLE
Resolution property support in start archive method

### ISSUE THREAD

**Issue by JayTokBox** [opentok/Opentok-Java-SDK#153]
This is a proposal to add resolution property support when creating archives
https://tokbox.com/developer/rest/#listing_archives

**Usage:**
```Java
ArchiveProperties properties = new ArchiveProperties.Builder().resolution("1280x720").build();
```
**Exceptions:**
At present only the string "1280x720" and "640x480" are supported (output being composed mode. Individual mode throws an exception no matter the value). Any other values will throw the following exception.  
```Java
case 400:
throw new RequestException("Could not start an OpenTok Archive. A bad request, check input archive properties like resolution etc.");
```

**Comment by msach22** [comment]
This has been released with `4.3.0`
