### ISSUE TITLE
generate JavaDoc and host the output on a gh-pages branch

### ISSUE THREAD

**Issue by aoberoi** [opentok/Opentok-Java-SDK#16]

**Comment by aoberoi** [comment]
javadoc is already generated by a gradle task. see `DEVELOPING.md`. The remaining part needed is to get it automatically pushed onto a gh-pages branch.

**Comment by SMadani** [comment]
https://www.javadoc.io/doc/com.tokbox/opentok-server-sdk/latest/index.html
