### ISSUE TITLE
startArchive with outputMode=Individual causes an error.

### ISSUE THREAD

**Issue by msach22** [opentok/Opentok-Java-SDK#174]
The error is happening because the SDK is setting a best fit layout even with outputMode set to Individual. OpenTok does not allow you to define a layout for individual archiving.

**Comment by sourabh-joshi** [comment]
How soon can this fix be expected out in a release?

**Comment by sourabh-joshi** [comment]
Also, will this fix resolve ticket #29544 ?

**Comment by msach22** [comment]
@sourabh-joshi This fix should go out Monday.

Yes, I believe so.

**Comment by sourabh-joshi** [comment]
Ok. Thanks.
