### ISSUE TITLE
HttpClient#stopBroadcast most messages attest that a broadcast cannot be started

### ISSUE THREAD

**Issue by meiao** [opentok/Opentok-Java-SDK#179]
Most of the start with 
> Could not start an OpenTok Broadcast.

**Comment by SMadani** [comment]
A complete rewrite of the SDK is in the works, will be integrated in [Vonage/vonage-java-sdk](https://github.com/Vonage/vonage-java-sdk). Can't provide any timelines for GA but there's currently a branch with beta versions.
