### ISSUE TITLE
HttpClient#stopBroadcast received a 409 from server for a broadcast that has already been stopped

### ISSUE THREAD

**Issue by meiao** [opentok/Opentok-Java-SDK#180]
The status code was 409 and this came in the body of the message
> {"code":19002,"message":"The broadcast has already been stopped","description":"The broadcast has already been stopped"}

It looks like it should have been a 404, according to 404's message.
Or can some treatment be done to display a better message instead of the default "The server response was invalid.".

**Comment by SMadani** [comment]
A complete rewrite of the SDK is in the works, will be integrated in [Vonage/vonage-java-sdk](https://github.com/Vonage/vonage-java-sdk). Can't provide any timelines for GA but there's currently a branch with beta versions.
