### ISSUE TITLE
Request Option to show name plate in live-streaming broadcast

### ISSUE THREAD

**Issue by colin-shah** [opentok/Opentok-Java-SDK#204]
Allow users to show Stream name in broadcast. This enhancement originates from an issue that a customer had with the Opentok SDK.   Is there any way in Opentok java SDK to show the name-plate of the broadcaster with the RTMP stream name in broadcast?

**Comment by dragonmantank** [comment]
Unfortunately compositing additional info is beyond the scope of the API, and the SDKs, at this time. I will look at putting it as a feature request for the API though. Thanks!

**Comment by JKazarian** [comment]
Adding name badgets to the stream is the highest demanded feature from our customers.
