### ISSUE TITLE
Basic HTTP proxy support

### ISSUE THREAD

**Issue by aoberoi** [opentok/Opentok-Java-SDK#53]
this came in as a need on opentok/opentok-node, so it might also be useful here.

**Comment by aoberoi** [comment]
http://asynchttpclient.github.io/async-http-client/apidocs/com/ning/http/client/AsyncHttpClientConfig.Builder.html#setProxyServer(com.ning.http.client.ProxyServer)

**Comment by aoberoi** [comment]
this should be added using the OpenTok builder pattern interface #94

**Comment by davideberlein** [comment]
Is this scheduled for a release?
One of our customers needs this very urgently!

**Comment by aoberoi** [comment]
@davideberlein its scheduled for the v3.0.0 milestone, but since we didn't have anyone specifically blocked on that milestone there wasn't a date. the earliest we can commit to that release would be in about one month. if you'd like to help push things along faster, we'd be happy to share the work and you can pick from anything in that milestone.
