### ISSUE TITLE
control default timeout

### ISSUE THREAD

**Issue by aoberoi** [opentok/Opentok-Java-SDK#59]
this could be useful: http://asynchttpclient.github.io/async-http-client/apidocs/com/ning/http/client/AsyncHttpClientConfig.Builder.html#setRequestTimeoutInMs(int)

the other kind of timeout is waiting for the body

**Comment by aoberoi** [comment]
this should be added via the OpenTok builder pattern interface #94

**Comment by yallen011** [comment]
This feature has been added to the SDK
