### ISSUE TITLE
2.3.0 version is not on maven central

### ISSUE THREAD

**Issue by grzesiekrzaca** [opentok/Opentok-Java-SDK#77]
Only 2.2.x where x {0,1,2}

http://gyazo.com/b580af41de40481fc81bde4a31865b67

**Comment by aoberoi** [comment]
@grzesiekrzaca thanks for pointing this out. there was a problem with the pom.xml formatting for version 2.3.0, so i've gone ahead and fixed that, and released 2.3.1, which is now available on maven.
